version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /opt/project
    volumes:
      - ./:/opt/project
    ports:
      - "3001:3000"
    command: bash -c "npm i && npm start"
